### ISSUE TITLE
Fix the test suite

### ISSUE THREAD

**Issue by parsonsmatt** [parsonsmatt/fourmolu#1]
Right now, the test suite is expecting everything to have 2 space indentation.

Reformatting it to have 4 space indentation would be great! Then we could publish to `stackage`.

**Comment by georgefst** [comment]
Well, I'm almost there, but curiously `fourmolu` fails to run on one (and only one) of the test cases:

``` bash
$ fourmolu data/examples/declaration/value/function/infix/do.hs 
AST of input and AST of formatted code differ.
  at data/examples/declaration/value/function/infix/do.hs:(2,3)-(4,12)
Please, consider reporting the bug.
```

`ormolu` (compiled from latest commit) works...

**Comment by parsonsmatt** [comment]
Looks like the offending code is this:

```haskell
-- in
main =
  do stuff
   `finally` do
     recover

-- out
main =
  do stuff
    `finally` do
      recover
```

This relies on the `do` keyword being two characters long. So, this is kind of a tricky thing about Haskell's layout rules, I think. My mental model is that, when you write a `do`, it lets you select a line/column for the indentation to care about. So if you write,

```haskell
    do   foo
         bar
```

This is fine, and in fact, necessary, because you put `foo` where you did. Why you did that, who knows? But the `bar` must start on the same column as the `foo`.

So the issue here is that we write:

```haskell
main = 
  do stuff
   `finally` do
     recover
```

The AST is grouping things like this:

```haskell
main = 
  (do stuff)
    `finally` (do
      recover)
```

And then we four space indent it over:

```haskell
main =
    do stuff
        `finally` do
            recover
```

This is grouped like so:

```haskell
main =
    do (stuff
        `finally` (do
            recover)
```

**Comment by georgefst** [comment]
Huh, interesting.

Actually fixing that would be far more than I came here to do, so I guess I'll just open the PR with the one failure.

**Comment by parsonsmatt** [comment]
Yeah I'm fine with that :)

**Comment by georgefst** [comment]
Seeing as I've now actually started using `fourmolu`, I'd like to get that remaining test case fixed. One option would be when we have:

``` haskell
do x
```

to just always force the `x` on to a new line. AFAICT, `ormolu` already does this for multi-line `do` blocks (and why would anyone ever write a single-line `do` anyway?!).
