### ISSUE TITLE
Command line options

### ISSUE THREAD

**Issue by georgefst** [parsonsmatt/fourmolu#12]
#10 introduced a `PrinterOpts` type, representing the space of all possible formatting configurations (at time of writing this is just indentation size). This should also be fully configurable from the command line, with the command line taking priority over config files.

**Comment by kukimik** [comment]
Hello! I'm a Haskell newbie (read some books + did some Exercism katas). I'd be happy to work on this issue.

**Comment by georgefst** [comment]
@kukimik Great!

A great place to start would be with a slight cleaning up: the existence of `PrinterOptsPartial` is a bit ugly, since it just replicates all the fields of 'PrinterOpts', wrapped in a `Maybe`. The best thing I can think of would be to change the definition of `PrinterOpts` to be parameterised - something like:

```haskell
data PrinterOpts f = PrinterOpts
  { poIndentStep :: f Int
  }
```

Then we would have the current `PrinterOpts` corresponding to `PrinterOpts Identity`, and `PrinterOptsPartial` corresponding to `PrinterOpts Maybe`. Type synonyms `PrinterOptsTotal` and `PrinterOptsPartial` might be useful.

We would need to define a function for merging partial opts (we could make this a `Semigroup` instance):

```haskell
mergePrinterOpts :: PrinterOptsPartial -> PrinterOptsPartial -> PrinterOptsPartia`
mergePrinterOpts = _
```

and a function for completing partial opts (by filling `Nothing` fields with the values from the second argument).

```haskell
completePrinterOpts :: PrinterOptsPartial -> PrinterOptsTotal -> PrinterOptsTotal
completePrinterOpts = _
```

For the actual argument parsing, look [here](https://github.com/parsonsmatt/fourmolu/blob/8dff2c6319a87a3c000145fd025dbd83e640e5e7/app/Main.hs#L189). You'll need to familiarise yourself with the [optparse-applicative](https://hackage.haskell.org/package/optparse-applicative) library, which is definitely worth knowing anyway if you want to build any serious Haskell CLI applications. A basic familiarity with [Applicative](https://hackage.haskell.org/package/base-4.14.0.0/docs/Prelude.html#t:Applicative) functors would help.

**Comment by parsonsmatt** [comment]
I'd also suggest - if the `f` parameter to `PrinterOpts` ends up being confusing or difficult to work with, don't be afraid to just copy/paste the datatype and put `Maybe` before every field. It's a little more duplication but the code will be much simpler and easier to write.

**Comment by georgefst** [comment]
Yeah sure, feel free to ignore the first half of my comment. I was just thinking out loud about something I'd like to fix up at some point.

It only really gets annoying when `PrinterOpts` inevitably gets more fields, and it can be fixed up by a separate, future, patch anyway (if it's even worth changing at all).

**Comment by kukimik** [comment]
Thanks for your suggestions! I think that for now I'll stick with the "boring" types, as suggested by @parsonsmatt . I see your point @georgefst, but I'm not quite sure how to convince the compiler that it is a good idea. :wink:

By the way, I had some trouble building the project with `stack` (due to the `aeson-1.5.2.0` dependency; vanilla ormolu worked out of the box). I've managed to overcome it using a custom snapshot based on `lts-16.3` with `aeson-1.5.2.0` included as an extra package.

I'm away for the weekend and will be able to get back to the issue next week.

**Comment by georgefst** [comment]
Ah, yes, sorry about that. I haven't been very careful about keeping the `stack` support up to date. We'll have CI set up to catch that sort of thing in the future: #11 

It would actually be really helpful if you could submit your changes to `stack.yaml` as a separate PR.
