### ISSUE TITLE
Add @georgefst to maintainers

### ISSUE THREAD

**Issue by parsonsmatt** [parsonsmatt/fourmolu#13]
- [x] Add to Hackage
- [ ] Add to maintainers in Cabal file

@georgefst what's your Hackage username?

**Comment by georgefst** [comment]
I'm `GeorgeThomas`.

Cheers.

**Comment by parsonsmatt** [comment]
You got it!

**Comment by georgefst** [comment]
Does this mean you're happy for me to make uncontroversial changes without approval? e.g. re-adding the two-space tests now that we have some configurability, merging upstream changes where there's no conflict, etc.

If you're happy with #6, I could actually get on with the 1.0 Hackage release.

**Comment by parsonsmatt** [comment]
I fully authorize you to do whatever you want with this project

**Comment by georgefst** [comment]
Close by ec4f206.
