### ISSUE TITLE
Indentation of 'where'

### ISSUE THREAD

**Issue by georgefst** [parsonsmatt/fourmolu#21]
I believe I'm not alone in preferring:

```haskell
x =
    y
  where
    y = 1
```

to:

```haskell
x =
    y
    where
        y = 1
```

It would be nice to have the option to indent `where`s half as much as everything else.

**Comment by parsonsmatt** [comment]
yes please!!!

**Comment by georgefst** [comment]
Turns out this one is, unsurprisingly, very simple to implement. But it'll be easier on top of #17.

Do we want this as the default behaviour? I'd vote yes.
