### ISSUE TITLE
List of lists formatting

### ISSUE THREAD

**Issue by anpryl** [parsonsmatt/fourmolu#43]
Tried to format list of lists:
```
x =
  [ [1, 2]
  , [2, 3]
  , [3, 4]
  ]
```
Result of formatting:
```
x =
  [
    [1, 2]
  ,
    [2, 3]
  ,
    [3, 4]
  ]
```

**Comment by georgefst** [comment]
Thanks for catching this just before release! This is a recent regression, and one that I'm surprised to see slipped through our test suite.
