### ISSUE TITLE
Configurable number of lines between top-level definitions

### ISSUE THREAD

**Issue by wraithm** [parsonsmatt/fourmolu#47]
We use 2 newlines between top-level definitions in our codebase. eg.

```haskell
f :: Int -> Int -> Int
f x y = square x + square y
  where
    square a = a * a


g :: Int -> Int
g z = f z z
```
as opposed to (single newline):
```haskell
f :: Int -> Int -> Int
f x y = square x + square y
  where
    square a = a * a

g :: Int -> Int
g z = f z z
```

It would be great if fourmolu had a configurable number of newlines between top-level definitions, such that we could set it to 2 instead of 1!

**Comment by georgefst** [comment]
I must say, that's not a style I've seen before. What's the reason for it?

Anyway, this is likely to be non-trivial, since the low-level combinators are designed to ensure that there's never more than one consecutive blank line inserted anywhere (e.g. calling `newline` is idempotent).

I'd take a look at a PR.

**Comment by wraithm** [comment]
It's just slightly easier to read the top-level declarations in isolation without it all being smushed together and looking the same.

I was kinda messing with a special newline function that's just for separations between top-level decls. This may be way way off:

```haskell
declNewline :: R ()
declNewline = do
    numNewlines <- getPrinterOpt poNewlinesBetweenDecls
    replicateM_ (numNewlines - 1) newlineRaw
    newline
```

Maybe this is absolutely horrible... idk.

It's not totally clear to me how separations between declarations happen, but I think I'm figuring that out.
