### ISSUE TITLE
Formatting changes AST in header haddock

### ISSUE THREAD

**Issue by georgefst** [parsonsmatt/fourmolu#53]
```hs
module M (
    -- | multi-line
    -- comment
    x,
) where
```

```
$ fourmolu M.hs --unsafe
module M (
    {- | multi-line
     comment
    -}
    x,
) where
```

The leading whitespace becomes part of the comment.

This will have been introduced by #30.

**Comment by brandon-leapyear** [comment]
Related:
```hs
module Foo
  ( -- * Foo
    {-| A long description that
        goes on

        More description
    -}
    foo
  ) where

foo :: Int
foo = 1
```
Running fourmolu on this gets me
```
AST of input and AST of formatted code differ.
  at Foo.hs:(3,5)-(7,6)
Please, consider reporting the bug.
```
Even though it is valid Haddock syntax

**Comment by georgefst** [comment]
Yeah, this is quite a serious issue actually, Ill try to revisit it soon.

Looking at [this comment](https://github.com/parsonsmatt/fourmolu/blob/master/src/Ormolu/Printer/Meat/Common.hs#L177) I'm quite surprised this happens. Presumably that logic is not getting applied within the export list.

**Comment by brandon-leapyear** [comment]
Actually, I've found general bad parsing of multiline Haddock docs. Moving to here: https://github.com/parsonsmatt/fourmolu/issues/63

**Comment by brandon-leapyear** [comment]
I think this can be closed in favor of https://github.com/parsonsmatt/fourmolu/issues/63
