### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by georgefst** [parsonsmatt/fourmolu#54]
The "About" field on GitHub should probably mention the expanded scope of the project (i.e. that it's no longer just about four spaces). Especially as this is reflected in the `<title>` element, so it's the first thing people see.

I think only @parsonsmatt has permissions to change that.

**Comment by parsonsmatt** [comment]
![image](https://user-images.githubusercontent.com/7310112/99097650-25d4f400-2595-11eb-9a62-010cc628c711.png)
 
Does that work for you?

**Comment by georgefst** [comment]
Perfect.
