### ISSUE TITLE
Magic comments don't completely disable formatting

### ISSUE THREAD

**Issue by brandon-leapyear** [parsonsmatt/fourmolu#69]
I would expect adding `{- FOURMOLU_DISABLE -}` to the very top of the file and running `fourmolu` would not change anything in the file, but it does change this:
```hs
{- FOURMOLU_DISABLE -}

class Bar a where
  bar1 :: a  


  bar2 :: a
```
to this:
```hs
{- ORMOLU_DISABLE -}

class Bar a where
  bar1 :: a

  bar2 :: a
```
It collapses multiple newlines into one, changes `FOURMOLU_DISABLE` to `ORMOLU_DISABLE`, and (you can't see it here) removes trailing whitespace

**Comment by brandon-leapyear** [comment]
Upstream issue: https://github.com/tweag/ormolu/issues/673

**Comment by brandon-leapyear** [comment]
@georgefst note: this is still an issue after the upstream ticket is resolved, because the `FOURMOLU_DISABLE` comment is changed to `ORMOLU_DISABLE`

**Comment by georgefst** [comment]
> the `FOURMOLU_DISABLE` comment is changed to `ORMOLU_DISABLE`

Thanks, I missed that. I'll open it as a separate issue.
